version: "3.9"

services:
  api:
    container_name: payroll_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
      - DB_NAME=payroll
    depends_on:
      - postgres
    networks:
      - payroll-network

  postgres:
    container_name: payroll_postgres
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payroll
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - payroll-network

volumes:
  pgdata:

networks:
  payroll-network:
    driver: bridge
